name: Update BLS Data Monthly

on:
  schedule:
    - cron: "0 0 1 * *"  # Runs on the 1st day of every month
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Data Collector
      run: python scripts/fetch_bls_data.py

    - name: Commit Updated Data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/bls_data.csv
        git commit -m "Automated data update"
        git push

